---
# Variable setup.
- name: Include variables
  include_vars: "packages.yml"

- name: ensure pre-defined default packages present
  yum:
    name: '{{ __system_packages }}'
    state: present

- name: ensure user-defined basic packages present
  yum:
    name: '{{ system_packages }}'
    state: present
  when: system_packages is defined

# Install MySQL package
- name: ensure mysql-devel present
  yum:
    name: mysql-devel
    state: present
